### PR TITLE
Make the game over music play in Step

### PR DESCRIPTION
**Pull request by SuperKoolRaven**

### CODE REVIEW

**Comment by itsjackielol** [comment]
change the mod folder name to “Soulles DX”, that should fix it

**Comment by SuperKoolRaven** [comment]
> 

what

**Comment by SuperKoolRaven** [comment]
> change the mod folder name to “Soulles DX”, that should fix it

What

**Comment by itsjackielol** [comment]
when you download the mod, change the name of the folder to "Soulles DX", the game over music won't play if the name is anything else

**Comment by SuperKoolRaven** [comment]
> when you download the mod, change the name of the folder to "Soulles DX", the game over music won't play if the name is anything else

oh okay

**Review by GrayAnimates — COMMENTED** [review]
thanks i forgot to change that line lol

**Comment by SuperKoolRaven** [comment]
> thanks i forgot to change that line lol

you're welcome m8

**Pull request merged**
